const MOBILE_BOARD_COPY = {
    en: {
        boardLabel: 'Mobile Board',
        filters: {
            all: 'All',
            conversation: 'Chat',
            note: 'Notes'
        },
        emptyCardsTitle: 'No cards yet',
        emptyNotesTitle: 'No notes yet',
        emptyDescription: 'Open a card to continue reading, or create a new one from the composer below.',
        cardLabel: 'Card',
        noteLabel: 'Note',
        untitledCard: 'Untitled Card',
        emptyNote: 'Blank note',
        imageToken: '[Image]',
        generating: 'Generating',
        saveIdle: 'Saved',
        saving: 'Saving',
        saveError: 'Save failed',
        open: 'Open',
        openFull: 'Open full',
        sprout: 'Sprout',
        expandTopics: 'Expand topics',
        uploadImage: 'Upload image',
        newNote: 'New note',
        readOnlyPlaceholder: 'Read-only mode',
        composerPlaceholder: 'Type to create or ask...',
        send: 'Send',
        instructions: 'Board instructions',
        settings: 'Settings',
        cardCount: '{count} cards'
    },
    zh: {
        boardLabel: '移动画板',
        filters: {
            all: '全部',
            conversation: '对话',
            note: '笔记'
        },
        emptyCardsTitle: '还没有卡片',
        emptyNotesTitle: '还没有笔记',
        emptyDescription: '先打开一张卡片看看内容，或者用底部输入条直接生成新卡片。',
        cardLabel: '卡片',
        noteLabel: '笔记',
        untitledCard: '未命名卡片',
        emptyNote: '空白笔记',
        imageToken: '[图片]',
        generating: '生成中',
        saveIdle: '已保存',
        saving: '保存中',
        saveError: '保存失败',
        open: '打开',
        openFull: '打开全文',
        sprout: '发散',
        expandTopics: '展开主题',
        uploadImage: '上传图片',
        newNote: '新建便签',
        readOnlyPlaceholder: '当前为只读模式',
        composerPlaceholder: '输入以创建或提问...',
        send: '发送',
        instructions: '画板指令',
        settings: '设置',
        cardCount: '{count} 张卡片'
    },
    ja: {
        boardLabel: 'モバイルボード',
        filters: {
            all: 'すべて',
            conversation: '会話',
            note: 'メモ'
        },
        emptyCardsTitle: 'カードはまだありません',
        emptyNotesTitle: 'メモはまだありません',
        emptyDescription: 'カードを開いて続きを読むか、下の入力バーから新しいカードを作成してください。',
        cardLabel: 'カード',
        noteLabel: 'メモ',
        untitledCard: '無題のカード',
        emptyNote: '空のメモ',
        imageToken: '[画像]',
        generating: '生成中',
        saveIdle: '保存済み',
        saving: '保存中',
        saveError: '保存失敗',
        open: '開く',
        openFull: '全文を開く',
        sprout: '発芽',
        expandTopics: 'トピックを展開',
        uploadImage: '画像をアップロード',
        newNote: '新しいメモ',
        readOnlyPlaceholder: '読み取り専用モード',
        composerPlaceholder: '入力して作成または質問...',
        send: '送信',
        instructions: 'ボード指示',
        settings: '設定',
        cardCount: '{count} 枚のカード'
    },
    ko: {
        boardLabel: '모바일 보드',
        filters: {
            all: '전체',
            conversation: '대화',
            note: '메모'
        },
        emptyCardsTitle: '아직 카드가 없습니다',
        emptyNotesTitle: '아직 메모가 없습니다',
        emptyDescription: '카드를 열어 내용을 보거나 아래 입력창에서 새 카드를 만들어 보세요.',
        cardLabel: '카드',
        noteLabel: '메모',
        untitledCard: '제목 없는 카드',
        emptyNote: '빈 메모',
        imageToken: '[이미지]',
        generating: '생성 중',
        saveIdle: '저장됨',
        saving: '저장 중',
        saveError: '저장 실패',
        open: '열기',
        openFull: '전체 열기',
        sprout: '발아',
        expandTopics: '주제 펼치기',
        uploadImage: '이미지 업로드',
        newNote: '새 메모',
        readOnlyPlaceholder: '읽기 전용 모드',
        composerPlaceholder: '입력하여 생성 또는 질문...',
        send: '전송',
        instructions: '보드 지시',
        settings: '설정',
        cardCount: '{count}개의 카드'
    }
};

export function getMobileBoardCopy(language = 'en') {
    return MOBILE_BOARD_COPY[language] || MOBILE_BOARD_COPY.en;
}
