const MOBILE_BOARD_COPY = {
    en: {
        boardLabel: 'iPhone Board',
        backToBoards: 'Back to boards',
        filtersLabel: 'Content filters',
        filters: {
            all: 'All',
            conversation: 'Chat',
            note: 'Notes'
        },
        emptyCardsTitle: 'No conversations yet',
        emptyNotesTitle: 'No notes yet',
        emptyDescription: 'Use the composer below to start a conversation.',
        cardLabel: 'Card',
        noteLabel: 'Note',
        untitledCard: 'Untitled Card',
        emptyNote: 'Blank note',
        imageToken: '[Image]',
        generating: 'Generating',
        saveIdle: 'Saved',
        saving: 'Saving',
        saveError: 'Save failed',
        open: 'Open',
        openFull: 'Open full',
        sprout: 'Sprout',
        expandTopics: 'Expand topics',
        uploadImage: 'Upload image',
        newNote: 'New note',
        readOnlyPlaceholder: 'Read-only mode',
        composerPlaceholder: 'Type to create or ask...',
        send: 'Send',
        instructions: 'Board instructions',
        settings: 'Settings',
        cardCount: '{count} cards',
        conversationCount: '{count} chats',
        modelLabel: 'Model',
        chooseModel: 'Choose model',
        modelAppliesToNewChats: 'Used for new chats',
        followGlobalModel: 'Follow global model',
        close: 'Close',
        messageCount: '{count} messages',
        imagePreview: 'Image preview',
        removeImage: 'Remove image'
    },
    zh: {
        boardLabel: 'iPhone 画板',
        backToBoards: '返回画板列表',
        filtersLabel: '内容筛选',
        filters: {
            all: '全部',
            conversation: '对话',
            note: '笔记'
        },
        emptyCardsTitle: '还没有对话',
        emptyNotesTitle: '还没有笔记',
        emptyDescription: '在底部输入问题，开始一段新对话。',
        cardLabel: '卡片',
        noteLabel: '笔记',
        untitledCard: '未命名卡片',
        emptyNote: '空白笔记',
        imageToken: '[图片]',
        generating: '生成中',
        saveIdle: '已保存',
        saving: '保存中',
        saveError: '保存失败',
        open: '打开',
        openFull: '打开全文',
        sprout: '发散',
        expandTopics: '展开主题',
        uploadImage: '上传图片',
        newNote: '新建便签',
        readOnlyPlaceholder: '当前为只读模式',
        composerPlaceholder: '输入以创建或提问...',
        send: '发送',
        instructions: '画板指令',
        settings: '设置',
        cardCount: '{count} 张卡片',
        conversationCount: '{count} 个对话',
        modelLabel: '模型',
        chooseModel: '选择对话模型',
        modelAppliesToNewChats: '将用于接下来创建的对话',
        followGlobalModel: '跟随全局模型',
        close: '关闭',
        messageCount: '{count} 条消息',
        imagePreview: '图片预览',
        removeImage: '移除图片'
    },
    ja: {
        boardLabel: 'iPhone Board',
        backToBoards: 'ボード一覧に戻る',
        filtersLabel: 'コンテンツフィルター',
        filters: {
            all: 'すべて',
            conversation: '会話',
            note: 'メモ'
        },
        emptyCardsTitle: '会話はまだありません',
        emptyNotesTitle: 'メモはまだありません',
        emptyDescription: '下の入力欄から新しい会話を始めてください。',
        cardLabel: 'カード',
        noteLabel: 'メモ',
        untitledCard: '無題のカード',
        emptyNote: '空のメモ',
        imageToken: '[画像]',
        generating: '生成中',
        saveIdle: '保存済み',
        saving: '保存中',
        saveError: '保存失敗',
        open: '開く',
        openFull: '全文を開く',
        sprout: '発芽',
        expandTopics: 'トピックを展開',
        uploadImage: '画像をアップロード',
        newNote: '新しいメモ',
        readOnlyPlaceholder: '読み取り専用モード',
        composerPlaceholder: '入力して作成または質問...',
        send: '送信',
        instructions: 'ボード指示',
        settings: '設定',
        cardCount: '{count} 枚のカード',
        conversationCount: '{count} 件の会話',
        modelLabel: 'モデル',
        chooseModel: '会話モデルを選択',
        modelAppliesToNewChats: 'これから作成する会話に使用します',
        followGlobalModel: 'グローバルモデルに従う',
        close: '閉じる',
        messageCount: '{count} 件のメッセージ',
        imagePreview: '画像プレビュー',
        removeImage: '画像を削除'
    },
    ko: {
        boardLabel: 'iPhone Board',
        backToBoards: '보드 목록으로',
        filtersLabel: '콘텐츠 필터',
        filters: {
            all: '전체',
            conversation: '대화',
            note: '메모'
        },
        emptyCardsTitle: '아직 대화가 없습니다',
        emptyNotesTitle: '아직 메모가 없습니다',
        emptyDescription: '아래 입력창에서 새 대화를 시작하세요.',
        cardLabel: '카드',
        noteLabel: '메모',
        untitledCard: '제목 없는 카드',
        emptyNote: '빈 메모',
        imageToken: '[이미지]',
        generating: '생성 중',
        saveIdle: '저장됨',
        saving: '저장 중',
        saveError: '저장 실패',
        open: '열기',
        openFull: '전체 열기',
        sprout: '발아',
        expandTopics: '주제 펼치기',
        uploadImage: '이미지 업로드',
        newNote: '새 메모',
        readOnlyPlaceholder: '읽기 전용 모드',
        composerPlaceholder: '입력하여 생성 또는 질문...',
        send: '전송',
        instructions: '보드 지시',
        settings: '설정',
        cardCount: '{count}개의 카드',
        conversationCount: '대화 {count}개',
        modelLabel: '모델',
        chooseModel: '대화 모델 선택',
        modelAppliesToNewChats: '새 대화에 사용됩니다',
        followGlobalModel: '전역 모델 따르기',
        close: '닫기',
        messageCount: '메시지 {count}개',
        imagePreview: '이미지 미리보기',
        removeImage: '이미지 삭제'
    }
};

export function getMobileBoardCopy(language = 'en') {
    return MOBILE_BOARD_COPY[language] || MOBILE_BOARD_COPY.en;
}
