(() => {
  window.__AIMAINMAP_FLOW_EXT__ = {
    MESSAGE_SEND: 'AIM_FLOW_SEND',
    MESSAGE_QUEUE_STATS: 'AIM_FLOW_QUEUE_STATS',
    MESSAGE_QUEUE_FLUSH: 'AIM_FLOW_QUEUE_FLUSH',
    MESSAGE_STORAGE_PROXY: 'AIM_FLOW_STORAGE_PROXY',
    STORAGE_UID_KEY: 'flowstudio_user_id',
    STORAGE_FALLBACK_PREFIX: '__aim_flow_ext__',
    FLOW_UID_MIN_LENGTH: 16,
    MAX_SELECTION_CHARS: 12000,
    STATUS_RESET_MS: 2400
  };
})();
